name: on_time
description: "A planner and note application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  persian_datetime_picker: ^2.7.0
  zoom_tap_animation: ^1.1.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/svg/
  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/yekan_bakh_hairline.ttf
        - asset: assets/fonts/yekan_bakh_light.ttf
        - asset: assets/fonts/yekan_bakh_regular.ttf
        - asset: assets/fonts/yekan_bakh_medium.ttf
        - asset: assets/fonts/yekan_bakh_bold.ttf
          weight: 700
        - asset: assets/fonts/yekan_bakh_fat.ttf
        - asset: assets/fonts/yekan_bakh_heavy.ttf

flutter_intl:
  enabled: true
