name: on_time
description: "A planner and note application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  zoom_tap_animation: ^1.1.0
  intl: ^0.19.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.3
  persian_datetime_picker: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  persian_horizontal_date_picker: ^0.1.7
  uuid: ^4.4.2
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1+2
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#DAE5EB"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/svg/
    - assets/images/icon/
  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/yekan_bakh_light.ttf
        - asset: assets/fonts/yekan_bakh_regular.ttf
        - asset: assets/fonts/yekan_bakh_bold.ttf
          weight: 700


flutter_intl:
  enabled: true
